### ISSUE TITLE
Language support for statements

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#146]
As pointed out in #145, language support involves a few main components:

1. setting up language support on the experiment website
2. setting up language support for the statements including back end and analysis
3. getting translations of content

This issue focuses on 2 and 3 (for the statements)

This is finished when statements can be served in the UI language and we have appropriate tracking of language and meaning on the back end, so that statement languages are noted, but also, statements across languages are able to be grouped i.e., by using a common statement ID and unique language IDs, or something like that. Further we should initially support any languages that we support in #145, and we can extend the automations and tests introduced in that issue.

**Comment by markwhiting** [comment]
As mentioned today, it's possible that statement translation should actually happen in the statements repo. But things like surveys and back end language support should happen in this repo.

**Comment by dankim444** [comment]
Statements are able to be rendered in the UI language. I created a new table that includes the first 20 rows of the original statements table and populated it with corresponding translations in the 10 languages. I then created an endpoint called api/experiment/test and called it in Layout.tsx to test that the statements were showing up properly. I've included some scripts in the server folder to help with setting up the table in your local machine.

**Comment by dankim444** [comment]
[duplicate_statements.zip](https://github.com/user-attachments/files/16034455/duplicate_statements.zip)
These are all the duplicate statements I was able find in the commonsense-statements repo.

**Comment by joshnguyen99** [comment]
Apart from exact matching, a good way to detect very similar strings is to use a distance metric.

Many metrics exist and you can consult some of them here: https://www.nltk.org/api/nltk.metrics.distance.html

**Comment by dankim444** [comment]
Hi, I am attaching a new file with all pairs of statements ranked by similarity scores in descending order. I only extracted the pairs that exceeded a similarity threshold of 97%, since I thought those were the most semantically "similar" statements, but you can adjust the threshold as you see fit in the cosine_similarity.py script in the statements repo.

I made one script that applies OpenAI's embeddings to vectorize the statement columns of the original statement files. I then created a separate script that utilizes sckit-learn's cosine similarity to extract the unique pairs that exceed a similarity of 97% and put them in a csv file for your analysis. I found a total of 413 pairs. Feel free to take a look at the script and validate the pipeline for computing and extracting similar pairs, as I had to reference several sources.

Here is the file: 
[high_similarity_statements.csv](https://github.com/user-attachments/files/16147806/high_similarity_statements.csv)

**Comment by JamesPHoughton** [comment]
Will be closed once updating the statements repo. Need to work out pipeline for translation from database back to database. Script that does the translation is currently running on local machine. It's going to be expensive, so need some checks built in. 

- Will be part of the normal pipeline for ingesting statements. 
- Will probably need to make custom snapshots to check that everything is working. Also need to update the dev snapshot from the production db (@amirrr), and maybe make this an automatic process in the future. 
- Dev snapshot pipeline should be something that checks production for diffs, and then automatically updates if necessary.

**Comment by JamesPHoughton** [comment]
@amirrr we're almost ready to PR this, it sounds like. Just need to check the front end (maybe an issue with updating the database?)

**Comment by JamesPHoughton** [comment]
Closed in @dankim444's head. But there are some breaking tests. 

Will be done by Friday, including outside @dankim444's head.
