### ISSUE TITLE
Evaluate user flow through the platform, plan issues and tests

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#158]
There are some edge cases where our user experience is inconsistent, e.g., https://github.com/Watts-Lab/commonsense-platform/issues/125, and others. 

We should: 

- [ ] Go through the main flows of the platform to check for inconsistencies like this. Especially impersonating users with different needs, e.g., a user who doesn't want to make an account, a user who has made an account and comes back (to each main page or URL), etc. 
- [ ] Create bug issues for any strange situations that show up during this process, specifying things like how to see the behavior, what it should be, or if that is not straightforward, document why it is strange that it behaves that way now (and we can discuss how it should behave), and finally, how the issue might be more generally incorporated into a software test that would avoid this class of failure in the future.

**Comment by markwhiting** [comment]
@dankim444 and @acao22 — this one could be split into a few, e.g., by focusing on different user flows. Feel free to split it up if you like. Of course also, it will generate more issues that we can split as needed too.

**Comment by acao22** [comment]
### As a user who already has an account:


1. **The page verification link takes you to**  -- Clicking on the verification page takes you back to the same page where it asks you to enter your email to register/sign in, although it actually successfully signed in -- the Dashboard is available, you just have to know to click on it in the Navbar. Maybe we could either change the welcome page to have a message saying "You successfully signed in" replacing the email input, or we could make the default page the Dashboard
<img width="700" alt="image" src="https://github.com/Watts-Lab/commonsense-platform/assets/119691957/b29a9395-7e0b-49f9-85d1-e419871dc108">


2. **Dashboard Setting** -- The settings on the Dashboard, once signed in, isn't really fleshed out yet

<img width="700" alt="Screenshot 2024-07-03 at 10 34 07 AM" src="https://github.com/Watts-Lab/commonsense-platform/assets/119691957/9fc9113b-e626-4d03-96ca-dd5e53343f35">




3. **Language Changing affecting Navbar** -- I think maybe we can add more flex width for the titles in the Navbar? For Japanese, Chinese, and Arabic, the rightmost title is shown vertically instead of horizontally so it's stretching the navbar a lot. For example, the Chinese one it should just say [仪表板] but for some reason there's an enter line between each character
<img width="700" alt="Screenshot 2024-07-03 at 10 38 50 AM" src="https://github.com/Watts-Lab/commonsense-platform/assets/119691957/553e956c-af1b-43cc-8256-15e432b08085">


4. **Dark Mode feedback modal** -- In Dark Mode, you can't really see the feedback popup because I think the text changes to white but the background still stays white as well. I think we can just switch it to dark and it should fix that
<img width="700" alt="image" src="https://github.com/Watts-Lab/commonsense-platform/assets/119691957/bf0f2bf4-a94d-4062-9221-797ed61add42">

Overall pretty good flow, those are all the things I found from this specific user point of view! I can take a look later at other types of user needs as well.

**Comment by dankim444** [comment]
## As a user who doesn't create an account

1. **Fix links to research publications in Research tab** -- The first link in the list of research publications directs you to the correct paper; however, the other two links do not. They both direct you to this link instead: https://arxiv.org/abs/2101.00100. This should be a very quick fix in Publications.tsx.
2. **Improve readability in language dropdown** -- The font color of unselected languages should be changed to something lighter for improved readability. We can adjust the CSS to ensure better contrast with the background.
<img width="1455" alt="image" src="https://github.com/Watts-Lab/commonsense-platform/assets/135999988/53bf79bd-a4ea-4425-a7ee-f8ce7735d380">

## As a user who created an account
1. **Incorporate data persistence for dashboard** -- When I close the tab after signing in and reopen the tab, I can no longer view the dashboard and am prompted to sign back in. The intended behavior should be that users do not need to sign back in after closing the tab.
2. **Add sign out button (?)** - Since there is a sign in button, maybe the platform could benefit from a sign out button as well? This is just a suggestion. We could probably add this under the delete account button in dashboard > settings.
3. **Create separate flows for account registration and sign in** -- I think creating an account and signing in should be treated as two separate flows. We can have one button that navigates new users to a registration page where they can enter their email or other required fields, and when the user submits, they can be shown a welcome/success message. Some tests for this would check that there isn't an account registered with the same email and that data entry was successful in the backend. We can keep the current flow for signing in as is, since this just involves entering an email.
<img width="1465" alt="image" src="https://github.com/Watts-Lab/commonsense-platform/assets/135999988/94c5db99-c7b5-45e1-87e3-487218e8cc40">

These are some of the things I was able to find. If I find any more, I'll update this comment and create issues.

**Comment by amirrr** [comment]
@acao22 Is this closable?

**Comment by acao22** [comment]
yes, it should be unless there are any other inconsistencies that #160 doesn't cover

> Quote reply
> Reference

**Comment by markwhiting** [comment]
OK, closing.
